### YamlMime:Tutorial
title: Administer flows
metadata:
  title: Test for metadata
items:
- durationInMinutes: 1
  content: |
    # Title
    *italic* 
    **bold** 
    ~~deleted~~ 
    [link](https://docs.microsoft.com)
