 ```yml
    ### YamlMime:PowershellModule
    uid: microsoft.powershell.core
    name: Microsoft.PowerShell.Core
    summary: |
      # Title
      *italic* 
      **bold** 
      ~~deleted~~ 
      [link](https://docs.microsoft.com)
  ```
